### ISSUE TITLE
No instance method ?

### ISSUE THREAD

**Issue by bogacg** [zensh/ui-autocomplete#19]
Autocomplete widget has an [instance method](http://api.jqueryui.com/autocomplete/#method-instance) but it is missing from this implementation.

I wanted to raise select event of autocomplete directive from my controller. What I was thinking is to get an instance then call instance.select().
Thanks

**Comment by zensh** [comment]
Added in v0.5.8

**Comment by bogacg** [comment]
Great, thanks.
I've just tried it.
Any idea how to translate this syntax to ui-autocomplete:
```
$(function () {  
  var companyList = $("#CompanyList").autocomplete({ 
      change: function() {
          alert('changed');
      }
   });
   companyList.autocomplete('option','change').call(companyList);
});
```
I've tried it like this (for **select**, instead of *change*):
```
            var inst = $scope.myOption.methods.instance();
            inst.options.select().call($scope.myOption);
```
it didn't work.

**Comment by zensh** [comment]
You could use it in this way:

```html
<input ng-model="language" ui-autocomplete="myOption">
```
where:
```js
$scope.myOption = {}
```
then:
```js
$scope.myOption = {}
var inst = $scope.myOption.methods.instance()
// or 
$scope.myOption.events. select()
// or some other methods/events
```

**Comment by bogacg** [comment]
Yes but shouldn't I need to provide event and ui parameters to select function?
it didn't work with select not providing any parameter: $scope.myOption.events.select()

```
            select: function (event, ui) {
              selectItem = ui;
              $timeout(function () {
                element.blur();
              }, 0);
            },
```

**Comment by zensh** [comment]
events should define in this way:
```js
$scope.myOption = {
  options: {
    html: true,
    onlySelectValid: true
  },
  events: {
    select: function(event, ui) {
      // do some thing
    },
    search: function(event, ui) {
      // do some thing
    }
  }
};
```

**Comment by bogacg** [comment]
That is my code in myOption:
```
options: {
            html: true,
            focusOpen: false,
            onlySelectValid: false,
            delay: 350
        },
        events : {
            select: function (a, b) {
                $(this).val(b.item.value);
                $scope.demoMod.selectedPeopleList.push(b.item.value);
            }
        }
```
This is the error I get:

TypeError: Cannot read property 'item' of undefined

**Comment by zensh** [comment]
I have updated demo: https://github.com/zensh/ui-autocomplete/commit/de46c14121c0ef2c7f20e0940bfe65ccd9d8fc72

You can try demo 1
