### ISSUE TITLE
Example for use of "groupLabel"

### ISSUE THREAD

**Issue by stschaefer** [zensh/ui-autocomplete#25]
Hi Yan,

thanks for your plugin. :)

Could you provide an example how to use the option groupLabel please.
How must the data be defined? How can I style the groups?

Thanks in advance. Greetings,
Stefan

**Comment by zensh** [comment]
Here is group label: **user**, **system**
![qq20150925-1 2x](https://cloud.githubusercontent.com/assets/863754/10091526/1cb758b0-636f-11e5-9414-dfd785a15009.png)

https://github.com/zensh/ui-autocomplete/blob/master/demo/demo.js#L10

**Comment by stschaefer** [comment]
Thanks for your quick help. :)
