### ISSUE TITLE
ui-autocomplete change pristine state on form load

### ISSUE THREAD

**Issue by Heliodromel** [zensh/ui-autocomplete#6]
Hi,

I'm using $pristine and $dirty form indicators to determine if there's some changes in the form and let the user know that he is about to leave the page with unsaved values.

When i apply ui-autocomplete on some input, it appears that the form pristine state is automatically changed to false (dirty = true) even if there is no changes in the form : after loading the form, state i already diry but user hasn't interact yet. Then if the user want to leave the page, a confirm message appears because my app has detected that the form state is dirty...

I made some research and i figure out that in ui-automplete, there is a call to angular method setViewValue ("ctrl.$setViewValue(ngModel.value);"). This method change the form pristine state.

Would you have any hack / fix for this problem ?

**Comment by mvarshavsky** [comment]
@zensh, do you mind explaining *why* that works, I'm just puzzled by how it accomplishes the desired behavior here
